# Generated by Django 4.2.1 on 2023-06-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_category_field_movies_category_movies_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Field',
            new_name='Tur',
        ),
        migrations.AlterField(
            model_name='movies',
            name='field',
            field=models.ManyToManyField(max_length=50, to='movies.field'),
        ),
    ]
