# Generated by Django 4.2.1 on 2023-06-17 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_rename_field_tur_alter_movies_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='field',
            field=models.ManyToManyField(max_length=50, to='movies.tur'),
        ),
        migrations.CreateModel(
            name='Watched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watched', models.ManyToManyField(null=True, to='movies.movies')),
            ],
        ),
    ]
