# Generated by Django 4.2.1 on 2023-06-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movies_field_watched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='field',
            new_name='tur',
        ),
    ]
