# Generated by Django 4.2.1 on 2023-06-17 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_field_movies_tur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Genre')),
            ],
        ),
        migrations.RemoveField(
            model_name='watched',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watched',
            name='watched',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='name',
            new_name='movie_name',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='tur',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Category name'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tur',
        ),
        migrations.DeleteModel(
            name='Watched',
        ),
        migrations.AddField(
            model_name='movies',
            name='genre',
            field=models.ManyToManyField(null=True, to='movies.genre'),
        ),
    ]
