# Generated by Django 4.2.1 on 2023-06-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_genre_remove_watched_user_remove_watched_watched_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='movie_name',
            new_name='name',
        ),
    ]
