# Generated by Django 4.2.1 on 2023-06-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_remove_watched_user_remove_watched_watched_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
