# Generated by Django 4.2.1 on 2023-06-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Movie name')),
                ('details', models.TextField(max_length=300, verbose_name='Movie details')),
                ('image', models.FileField(blank=True, null=True, upload_to='photos')),
            ],
        ),
    ]
