# Generated by Django 4.2.1 on 2023-06-17 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_watched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='image',
            new_name='photo',
        ),
    ]
