# Generated by Django 4.2.1 on 2023-06-17 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_rename_image_movies_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='photo',
            new_name='image',
        ),
    ]
